import { Montserrat } from "next/font/google";
import "./globals.css";

const montserratSans = Montserrat({
    variable: "--font-montserrat-sans",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="fr"
            className={`${montserratSans.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">{children}</body>
        </html>
    );
}
